# Generated by Django 6.0.6 on 2026-06-06 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_category_options_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='Author',
            new_name='author',
        ),
    ]
